name: frido
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=10.2
  - pytorch=1.7.0
  - torchvision=0.8.1
  - numpy=1.19.2
  - pip:
    - opencv-python==4.1.2.30
    - albumentations==0.4.3
    - einops==0.3.0 
    - imageio==2.9.0 
    - imageio-ffmpeg==0.4.2 
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - more-itertools==8.12.0 
    - numpy==1.19.2
    - omegaconf==2.0.0 
    - opencv-python-headless==4.1.2.30
    - pandas==1.4.1
    - Pillow==9.0.1
    - pudb==2019.2    
    - Pygments==2.11.2
    - Pympler==1.0.1
    - python-dateutil==2.8.2
    - torch-fidelity==0.3.0
    - pytorch-lightning==1.0.8 
    - PyYAML==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - scikit-image==0.19.2
    - scipy==1.8.0
    - setuptools==58.0.4
    - six==1.16.0
    - streamlit==1.7.0 
    - terminado==0.13.3
    - test-tube==0.7.5 
    - timm==0.4.5
    - tokenizers==0.10.3
    - tornado==6.1
    - tqdm==4.63.0
    - transformers==4.3.1 
    - typing-extensions==3.10.0.2
    - urllib3==1.26.9
    - -e .