model:
  base_learning_rate: 1.e-6   # set to target_lr by starting main.py with '--scale_lr False'
  target: frido.models.diffusion.frido.FridoDiffusion
  params:
    adopted_scale_factor: True
    noise_mix_ratio: 0.1
    first_stage_key: image
    cond_stage_key: objects_bbox
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    image_size: 64
    channels: 6
    cond_stage_trainable: true
    conditioning_key: crossattn
    scale_by_std: True
    monitor: 'val/loss'
    unet_config:
      target: frido.modules.diffusionmodules.pyunet.PyUNetModel
      params:
        use_split_head: true
        split_embed_dim_list: [3, 3]
        use_SPADE_norm: true
        image_size: 64
        in_channels: 6
        out_channels: 6
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 640
        num_stage: 2

    first_stage_config:
      target: taming.models.msvqgan.VQModelInterface
      params:
        ckpt_path: exp/msvqgan/openimage_f8f4/model.ckpt
        embed_dim: [3, 3]
        n_embed: [4096, 4096]
        edconfig:
          multiscale: 2
          double_z: False
          z_channels: [3, 3]
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [64]
          dropout: 0.0
        ddconfig:
          double_z: False
          z_channels: 6
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [64]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss

    cond_stage_config:
      target: frido.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 640
        n_layer: 32
        max_seq_len: 96
        use_tokenizer: False

    plot_sample: False 
    plot_inpaint: False 
    plot_denoise_rows: False
    plot_progressive_rows: False
    plot_diffusion_rows: False
    plot_quantize_denoised: True

data:
  target: scripts.sample_diffusion.DataModuleFromConfig
  params:
    batch_size: 12
    validation:
      target: taming.data.annotated_objects_coco.AnnotatedObjectsCoco
      params:
        data_path: ../datasets/coco/2017  # substitute with path to full dataset
        OI_cate_path: frido/data/classes.csv
        split: validation
        keys: [image, objects_bbox, file_name, annotations]
        no_tokens: 1024
        target_image_size: 256
        min_object_area: 0.02
        min_objects_per_image: 2
        max_objects_per_image: 30
        crop_method: center
        random_flip: false
        use_group_parameter: true
        encode_crop: true
    test:
      target: taming.data.annotated_objects_coco.AnnotatedObjectsCoco
      params:
        data_path: ../datasets/coco/2017  # substitute with path to full dataset
        OI_cate_path: frido/data/classes.csv
        split: validation
        keys: [image, objects_bbox, file_name, annotations]
        no_tokens: 1024
        target_image_size: 256
        min_object_area: 0.02
        min_objects_per_image: 2
        max_objects_per_image: 30
        crop_method: center
        random_flip: false
        use_group_parameter: true
        encode_crop: true
